### ISSUE TITLE
BUG: Issue with `node:` namespace in modules

### ISSUE THREAD

**Issue by exoRift** [hegemonic/requizzle#13]
Hi! I'm trying to make a JSDoc template that compiles React with Vite. Unfortunately, Vite imports `node:path` and `node:fs` which causes Requizzle to throw an error when it attempts to do an `fs.readFileSync` and sinc JSDoc forces the publish script to run with Requizzle, there's no workaround for it.

**Comment by hegemonic** [comment]
Thanks for the heads up! This issue is fixed on `main`, and I'll release a new version with the fix soon. If you reinstall JSDoc, you should pick up the new version automatically.
